### PR TITLE
Appveyor fix

### PR DESCRIPTION
**Pull request by benbalter**

### CODE REVIEW

**Comment by benbalter** [comment]
@mertkahyaoglu tracked this down to https://github.com/bundler/bundler/issues/5337 (or something related). From what I can tell, Bundler v0.14 was released this weekend, and it's not quite ready for prime time, at least not on windows. This PR now simply locks Bundler ot v0.13, so the build can proceed.

**Comment by mertkahyaoglu** [comment]
Wow 😮  Thank you so much for helping out @benbalter

**Comment by mertkahyaoglu** [comment]
@benbalter Is it possible in appveyor to add me as a team member so I can rebuild?

**Comment by benbalter** [comment]
> Is it possible in appveyor to add me as a team member so I can rebuild?

I *think* you should now have access...

**Comment by mertkahyaoglu** [comment]
Got an e-mail about it saying `User Ben Balter has added you to AppVeyor account benbalter as collaborator with User role.`

I think you added me to the account not the repo. I found an issue about this in the forum. Quoting;

> You can define a custom Role, add created user to that role and then apply permissions for specific project on its settings page.

**Pull request merged**
