### PR TITLE
Fix updating pages/documents

### LINKED ISSUE #79: Markdown edit box is writing rendered HTML, not raw markdown
E.g.:

screen shot 2016-07-28 at 11 43 10 am

Steps to reproduce:

1. Navigate to http://localhost:4000/admin/pages/page.md
2. Modify the markdown
3. Hit save

Expected:

Update markdown is saved and displayed

Actual:

* `<h1 id="test-page">Test Page</h1>` is saved to disk and displayed.
* `raw_content` metadata filed is saved with the content

@mertkahyaoglu this may be a miscommunication / need to change on the server side. I'm guessing you're sending `raw_content` as a metadata field, in addition to `body`?

### LINKED ISSUE #80: Saving a page saves its computed/default front matter
Steps to reproduce:

1. Navigate to http://localhost:4000/admin/pages/page.md
2. Change the body content
3. Hit save

Expected:

Only the content is updated

Actual:

All fields written to disk including `dir` and front matter defaults.

### PR DESCRIPTION
**Pull request by mertkahyaoglu**
Closes #79 
Closes #80

### CODE REVIEW

**Comment by benbalter** [comment]
@parkr @jldec and chance you could 👀 this and https://github.com/jekyll/jekyll-admin/pull/60?

**Comment by jldec** [comment]
> any chance you could 👀 this

@benbalter - i'm working on getting myself familiar enough with how to repro issues and how this stack works so that i can offer meaningful feedback. I expect to be closer next week, so please don't let me block progress in the meantime.

**Comment by mertkahyaoglu** [comment]
@benbalter I think this is ready.

**Comment by benbalter** [comment]
I didn't do a deep dive on the code, but the fixtures and changes regarding the scheme LGTM.

**Comment by benbalter** [comment]
Merged https://github.com/jekyll/jekyll-admin/pull/85 and still LGTM (to get CI to pass).

**Comment by benbalter** [comment]
LGTM.

**Comment by mertkahyaoglu** [comment]
@benbalter I need one more LGTM please 😁

**Comment by parkr** [comment]
LGTM.

**Pull request merged**
