### PR TITLE
DataGUI: Fix DatePicker & StaticFilePicker CSS

### LINKED ISSUE #384: DatePicker & StaticFilePicker are broken in GUI mode
screen shot 2017-05-17 at 21 55 04

### PR DESCRIPTION
**Pull request by ashmaroli**
Fix #384 

### Samples
spl-fields
date-picker
time-picker

### CODE REVIEW

**Comment by mertkahyaoglu** [comment]
I can't click nested items.

**Comment by ashmaroli** [comment]
> I can't click nested items.

Please explain further.

**Comment by ashmaroli** [comment]
rewrote the `datagui.scss` to remove some convoluted declarations, additionally re-ordering CSS properties consistently for improved maintainability

**Comment by ashmaroli** [comment]
would be cool if `date`, `file` and `image` functionality be extended to their plural counterparts set to an array of corresponding elements.
e.g.
```yaml
image: logo.gif
images:
  - foo.png
  - bar.jpg
  - baz.gif
```

**Pull request merged**
