### PR TITLE
Initial release

### PR DESCRIPTION
**Pull request by mertkahyaoglu**
🎉 

Fixes https://github.com/jekyll/jekyll-admin/issues/128.

### CODE REVIEW

**Comment by benbalter** [comment]
hooray!

**Comment by mertkahyaoglu** [comment]
celebrate

**Comment by DirtyF** [comment]
Congrats! 

Shouldn't this release appear on https://github.com/jekyll/jekyll-admin/releases ?

**Comment by mertkahyaoglu** [comment]
@DirtyF Thanks @DirtyF 

It does 😄

**Pull request merged**
