### PR TITLE
Sort documents by date

### LINKED ISSUE #95: Show post date in post index list
It'd be nice to show the date of posts for the post list (and to sort reverse chronologically by date, which we can do on the API level, if you want).

Other collections could theoretically have dates, but there's no programatic way to tell, so I think it's fine just to do this for posts for now.

### PR DESCRIPTION
**Pull request by mertkahyaoglu**
Closes #95

### CODE REVIEW

**Comment by benbalter** [comment]
LGTM. Is that going to be ascending or descending? (I think it should be latest first)

**Comment by mertkahyaoglu** [comment]
Yes, it is latest first.

**Comment by mertkahyaoglu** [comment]
This works for only post documents because other collections' documents have the same date which is the start date of the server. I think we can fix that later on.

**Comment by benbalter** [comment]
> This works for only post documents because other collections' documents have the same date which is the start date of the server. I think we can fix that later on.

👍

**Pull request merged**
