### PR TITLE
Fix typos in documentation

### PR DESCRIPTION
**Pull request by ashmaroli**
Fixes numerous typos in various documentation files.

### CODE REVIEW

**Comment by mertkahyaoglu** [comment]
Not sure it should be `back end`, `backend` or `back-end`. Same for the `frontend`. Other than that LGTM.

/cc @jekyll/documentation

**Comment by ashmaroli** [comment]
Till I find a more reliable source, this should suffice:
[Front End & Back End](https://en.wikipedia.org/wiki/Front_and_back_ends)
:smiley:

**Comment by ashmaroli** [comment]
Found a reliable source for citation:
[GCC Coding Convention](http://gcc.gnu.org/codingconventions.html#Spelling)

`front end` if **noun** ( Javascript front end )
`front-end` if **adjective** ( front-end server )

**Comment by IanLee1521** [comment]
LGTM. Based on those conventions, I think all of the `back end`s and `front end`s look correct.

**Comment by mertkahyaoglu** [comment]
Let's merge this when you update.

**Comment by benbalter** [comment]
Thanks @ashmaroli!

**Comment by ashmaroli** [comment]
@jekyllbot: remove pending-feedback label :smile:

**Pull request merged**
