### PR TITLE
Add directory support for static files

### LINKED ISSUE #201: Feature request: Specify folder to upload static files to
Right now, you can only upload static files to the base directory of the site. It would be nice, if you could an option to upload to a specific directory like 'images'.

### PR DESCRIPTION
**Pull request by ashmaroli**
- [x] Update API
- [x] Add front-end support
- [x] add coverage
- [x] Update documentation

Partially resolves #201 

### `/admin/staticfiles/assets`
(sample user directory)

static-dirs

### `/admin/staticfiles/index`
(static page. no other actions)

static-index

### CODE REVIEW

**Comment by ashmaroli** [comment]
@mertkahyaoglu @benbalter Did you guys get a chance to look into this?

**Comment by mertkahyaoglu** [comment]
Tested locally. It's looking great. Great job 👍  
I'm going to review the code soon.

**Comment by gengsa** [comment]
@ashmaroli  How about read some diretory from _config.yml, so i can specify my own config. Or even directly to the sub-folder. Look forward to your submission.

**Comment by ashmaroli** [comment]
@gengsa can you elaborate a little bit more.. with a small example?
Also, this feature is currently available via [`jekyll-manager`](https://github.com/ashmaroli/jekyll-manager) if you want to give it a try..

**Comment by gengsa** [comment]
@ashmaroli  I have tried your [jekyll-manager](https://github.com/ashmaroli/jekyll-manager). I want to specify my own **static files base directory**, like **/images** or **/assets/images**. And with some sub-directory, just like
> /images/image1.png,
> /images/foods/images2.png,
> /images/foods/image3.png,

Maybe some other directory. Thank you very much.

**Comment by gengsa** [comment]
@ashmaroli  Thanks your [jekyll-manager](https://github.com/ashmaroli/jekyll-manager), it's what i want. Hope you merge into [jekyll/jekyll-admin](https://github.com/jekyll/jekyll-admin). Thanks very much.

**Comment by ashmaroli** [comment]
Many of the features in `jekyll-manager` are already under review for merge into Jekyll Admin..
Only a matter of time..

**Comment by renshuki** [comment]
Any plan to merge this PR? It would be great.

**Comment by mertkahyaoglu** [comment]
Could merge this when conflicts are resolved.

**Comment by ashmaroli** [comment]
@mertkahyaoglu The conflicts are too complex for me to resolve. Will you be able to handle them..? Else, I shall close this..

**Comment by mertkahyaoglu** [comment]
@ashmaroli Ok. I take a look at it.

**Comment by bernardomed** [comment]
HI all,

Any update on this?

Kind regards,

**Pull request merged**
