### PR TITLE
Notification System

### LINKED ISSUE #119: Notification System
- [ ] Show notifications for errors. ([example](http://igorprado.com/react-notification-system/))

### PR DESCRIPTION
**Pull request by mertkahyaoglu**
Currently the frontend notify users

- [x] if API does not respond
- [x] if they enter invalid YAML content for the configuration and data files
- [x] when they upload a static file successfully.

**Preview;**
screen shot 2016-08-19 at 11 39 42 pm

Closes #119

### CODE REVIEW

**Comment by benbalter** [comment]
Really like this. Tested locally and suggest, if not hard, this should also work for Data files with invalid YAML (as it does for config files). Also found an unrelated bug, which I'll open separately.

**Comment by benbalter** [comment]
@mertkahyaoglu your call if you'd like to implement this for data files, otherwise....

LGTM.

**Comment by mertkahyaoglu** [comment]
@benbalter Implemented for data files 👍

**Comment by mertkahyaoglu** [comment]
@benbalter Any final comments for this. It's ready to go 💥

**Comment by benbalter** [comment]
LGTM.

**Pull request merged**
