### PR TITLE
Create documents and pages

### PR DESCRIPTION
**Pull request by mertkahyaoglu**

### CODE REVIEW

**Comment by benbalter** [comment]
First off, this 

screen shot 2016-08-01 at 3 02 33 pm

and this

screen shot 2016-08-01 at 3 02 38 pm

👌 Really nice touches.

Everything looks great, except I'm getting one error.

screen shot 2016-08-01 at 3 01 26 pm
screen shot 2016-08-01 at 3 02 12 pm

Steps to reproduce:

1. Create a new post (click save)
2. Immediate click "posts" in the sidebar

Otherwise, LGTM.

**Comment by benbalter** [comment]
LGTM.

**Comment by mertkahyaoglu** [comment]
Thank you @benbalter. Little mistake by me. Fixed and reorganized listing views.

**Comment by benbalter** [comment]
:metal: LGTM.

**Pull request merged**
