### PR TITLE
Front-end served from `/admin`

### LINKED ISSUE #22: Frontend should assume it's served from `/admin` not the server root
Right now, loading `index.html` assumes that paths to assets (e.g., `bundle.js`, `style.css`) are all served from the server root. Instead, the server should assume it's served from the `/admin` directory (e.g., `/admin/bundle.js`).

### PR DESCRIPTION
**Pull request by mertkahyaoglu**
Closes #22

### CODE REVIEW

**Comment by parkr** [comment]
@mertkahyaoglu Would it be possible to specify a prefix _once_ instead of every time?

**Comment by mertkahyaoglu** [comment]
@parkr Yeah, thought about it, lazy me 😁  Doing right now.

**Comment by benbalter** [comment]
@mertkahyaoglu This is awesome. Thanks for being so responsive. If tests pass, and pending @parkr and @jldec's feedback, feel free to merge at you convenience so that you're not blocked.

One question: Since it's a single page app, do you want all requests to `/admin/*` that are not to existing static files to render the index? If so, an easy fix.

**Comment by mertkahyaoglu** [comment]
@benbalter That's a good idea 👍 

There is one problem with serving single page app. Let's say I visited `/admin/collections` through the sidebar link. There is no problem. But if I type that link by hand or refresh the browser, sinatra cannot find the route.

**Comment by mertkahyaoglu** [comment]
I can't seem to ignore `spec/fixtures/site/Gemfile.lock` file. I updated the .gitignore, still no work 😯  Should I give it to the full path 😬

**Comment by benbalter** [comment]
> I can't seem to ignore spec/fixtures/site/Gemfile.lock file. I updated the .gitignore, still no work. 

Feel free to cherry pick https://github.com/jekyll/jekyll-admin/pull/27/commits/a7fc2815e008e161a9e3f00afaa98466bd09642d (or wait for it to merge).

**Comment by benbalter** [comment]
> do you want all requests to /admin/* that are not to existing static files to render the index?

Implemented via https://github.com/jekyll/jekyll-admin/issues/27.

**Comment by mertkahyaoglu** [comment]
@benbalter I reverted the commit. We can merge #27

**Pull request merged**
