### PR TITLE
Updating depreciated "gems" to "plugins"

### PR DESCRIPTION
**Pull request by scottmathson**

### CODE REVIEW

**Comment by mertkahyaoglu** [comment]
Thanks @scottmathson 👍

**Comment by scottmathson** [comment]
Absolutely! Thank YOU for making Jekyll Admin, not using it now, but have checked it out - love it.

**Comment by mertkahyaoglu** [comment]
Actually this should have been `plugins_dir`right ? 😄

**Comment by scottmathson** [comment]
Everything is working fine, locally, on my end here as-is. Don't see the need to definitely layout out `plugins_dir:`. We're still simply grabbing the latest, published jekyll-admin gem when initially running `bundle install`.

**Comment by scottmathson** [comment]
I've been cd'ed and testing in `jekyll-admin/spec/fixtures/site` this whole time, FYI.

**Comment by mertkahyaoglu** [comment]
Hmm. Could you do `script/server-frontend` ? And which ruby version are you using?

**Comment by scottmathson** [comment]
`ruby 2.4.0 (2016-12-24) [x86_64-darwin16]`

**Comment by mertkahyaoglu** [comment]
It was about my old Gemfile.lock 😬  No problem now. Thanks again @scottmathson

**Pull request merged**
