### PR TITLE
Slightly better messages when search fail

### PR DESCRIPTION
**Pull request by DirtyF**
When search do not return anything, it feels odd to read "You don't have any pages." 
Tried to make it more accurate with this proposition.

### CODE REVIEW

**Comment by benbalter** [comment]
LGTM. Thanks @DirtyF! @mertkahyaoglu what do you think?

**Comment by mertkahyaoglu** [comment]
Let's say, there are not any pages on the site. We are going to get `No matching pages found` at the beginning, even though we are not searching anything. The message should be specific to only searching. We need to find a way to separate them.

**Comment by Crunch09** [comment]
Maybe `No XYZ found` instead of `No matching XYZ found`? I think this would work well in both cases.

**Comment by mertkahyaoglu** [comment]
Adding this might work;
``` javascript
{
    !filterByFilename(files, utils.input).length && <h1>{`No matching data files found.`}</h1>
}
```

**Comment by mertkahyaoglu** [comment]
@Crunch09 That also works.

**Comment by DirtyF** [comment]
OK, thanks for the explanation @mertkahyaoglu, I'll update with @Crunch09 proposition for now.

**Comment by mertkahyaoglu** [comment]
Thanks @DirtyF 👍

**Comment by Crunch09** [comment]
@DirtyF  Thanks for the mention 😆

**Comment by benbalter** [comment]
@mertkahyaoglu if this looks good to you, feel free to merge. :smile:

**Comment by mertkahyaoglu** [comment]
LGTM

**Pull request merged**
