### PR TITLE
Don't trim spaces from metadata value-field

### LINKED ISSUE #364: Impossible to put spaces in metadata field
### Description:

Just a quick issue so that @ashmaroli can track it properly :)
It is now impossible to put space between words after the application of #338.

### Steps to reproduce:

Put a full sentence as an excerpt in a metadata field.

### I expected the following:

To be able to put a full sentence as an excerpt and submit it.

### But got the following, instead:

I can't put spaces between words, the space character is deleted as soon as written. It is possible to copy/paste sentences.

### Other details:

As suggested by @ashmaroli, typing between quotes is an efficient workaround :)

### PR DESCRIPTION
**Pull request by ashmaroli**
Fixes #364 
A regression was caused by #339 wherein the eventhandler attached to `.value-field` prevents typing a space character before the next word.

`<TextareaAutosize />` doesn't have an `onBlur` prop to dispatch trimming effectively. So simply reverting to old behavior.

### CODE REVIEW

**Comment by mertkahyaoglu** [comment]
Of course this happens 😬  Whenver the field changes it will trim the white-spaces around it. We should trim only when saving.

**Comment by ashmaroli** [comment]
> We should trim only when saving.

Yep, but that would mean, opening the entire `Object`, processing every `value` and `sub-value` before sending the payload..

**Comment by mertkahyaoglu** [comment]
@ashmaroli Could you try the following for `TextareaAutosize`;

```javascript
onBlur={(e) => console.log(e.target.value.trim())}
```

**Comment by ashmaroli** [comment]
> Could you try the following

@mertkahyaoglu Tried it. While the `<textarea>` HTML element correctly has the spaces trimmed, the resulting front matter meta contains those spaces. Even existing tests pass (which should fail if this *workaround* had worked)

**Comment by mertkahyaoglu** [comment]
That's because trimmed value is not passed to the metadata store. We should call `updateFieldValue` action when blurred to do that. 

```javascript

onBlur={(e) => updateFieldValue(nameAttr, e.target.value.trim())}

```

But I'm not sure which of these two method is better. Calling an extra action onBlur or processing every value and sub-value before sending the payload 🤔  First looks easier.

**Comment by ashmaroli** [comment]
> We should call `updateFieldValue` action

This works! Will push an update :smiley: :+1:

**Pull request merged**
