### PR TITLE
Release v0.4.0

### PR DESCRIPTION
**Pull request by mertkahyaoglu**
Let's release v0.4.0 so that people benefit from new directories api and some other improvements 🎉

### CODE REVIEW

**Comment by ashmaroli** [comment]
For some reason, the `scrollMargin` setting from `react-ace-4.1.5` doesn't seem to be working in the release version. But it works perfectly under a `script/server-frontend` session. Please verify.

**Comment by mertkahyaoglu** [comment]
I can't see it in the dev mode either 😕

**Comment by ashmaroli** [comment]
> I can't see it in the dev mode either

is your `react-ace` module at `4.1.5`?

**Comment by mertkahyaoglu** [comment]
Oh, you're right. I'm seeing top margin on dev and nothing on release version, strange 😒

**Comment by mertkahyaoglu** [comment]
I guess I need to reinstall `node_modules` before releasing.

**Comment by ashmaroli** [comment]
> I guess I need to reinstall node_modules before releasing.

:+1:  But I think its only needed when one of the modules get bumped via a PR..

**Pull request merged**
