### PR TITLE
support directories for data files more robustly

### PR DESCRIPTION
**Pull request by ashmaroli**
Came across a bug that prevented me from accessing `/#{API}/data` via GIT BASH.

This refactors the implementation for directory support for data files

### CODE REVIEW

**Comment by ashmaroli** [comment]
@fowlie, can you check if this patch causes any test failures at your end?
To pull this to your system, simply run the following within the repo directory:
```
$ git checkout -b test-branch
$ git pull upstream pull/396/head
```

**Comment by fowlie** [comment]
@ashmaroli, yes, running `script/cibuild` on this PR causes these errors (same errors I ended up with in issue #394):
```
Failures:

  1) collections an individual collection entries lists directories
     Failure/Error: expect(entries.first["name"]).to eq("more posts")
     
       expected: "more posts"
            got: "test"
     
       (compared using ==)
     # ./spec/jekyll-admin/server/collection_spec.rb:94:in `block (4 levels) in <top (required)>'

  2) JekyllAdmin::URLable data files knows the API URL
     Failure/Error: expect(subject.api_url).to eql(api_url)
     
       expected: "http://localhost:4000/_api/data/data_file.yml"
            got: "http://localhost:4000/_api/data/movies/genres/fiction.yml"
     
       (compared using eql?)
     # ./spec/jekyll-admin/urlable_spec.rb:92:in `block (3 levels) in <top (required)>'

Finished in 33.68 seconds (files took 1.47 seconds to load)
176 examples, 2 failures

Failed examples:

rspec ./spec/jekyll-admin/server/collection_spec.rb:90 # collections an individual collection entries lists directories
rspec ./spec/jekyll-admin/urlable_spec.rb:91 # JekyllAdmin::URLable data files knows the API URL
```

**Comment by ashmaroli** [comment]
@fowlie Thank you for testing. Sorry I couldn't isolate the cause of failures at your end, but as a consolation, I was able to pick the bug addressed in this PR because I tested in a different environment than my usual dev env. So, thanks once again. :smiley:

**Comment by fowlie** [comment]
@ashmaroli No problem, happy to help :smile:

**Comment by mertkahyaoglu** [comment]
Can we make use of PathHelper module here?

**Comment by mertkahyaoglu** [comment]
I think we should handle this in PathHelper module which contains all path related logic. A few conditional statements would do the trick, I guess.

**Comment by ashmaroli** [comment]
> I think we should handle this in PathHelper module which contains all path related logic. A few conditional statements would do the trick, I guess.

True but since the module is both `included`and `extended` its going to be slightly tricky..

**Comment by ashmaroli** [comment]
DISCLAIMER: since its been so long, I don't quite remember what my PRs were about.. :laughing:

**Comment by mertkahyaoglu** [comment]
Yeah, sorry for that 😬  I could barely find time for several months. But from now on, I believe I can spare more time to Jekyll Admin. It's about time for major changes 🎉

**Comment by ashmaroli** [comment]
Excited to see what you'll be bringing to the table.. :smiley:

**Pull request merged**
