### PR TITLE
Add option to change homepage

### LINKED ISSUE #156: Dashboard main page, rather than being welcomed by posts or pages
Right now when I enter Jekyll admin, I'm greeted my `pages` directory, which I'm rarely going to edit. Though this behavior might be specific to me since I included a `_pages` directory. But either way, whether posts or pages, it would be more pleasing to be greeted by a dashboard main page.

### PR DESCRIPTION
**Pull request by mertkahyaoglu**
Closes #156

### CODE REVIEW

**Comment by ashmaroli** [comment]
What if the user would like to have the `data` or `drafts` route as their homepage?

**Comment by mertkahyaoglu** [comment]
@ashmaroli I didn't think anybody would want that 😅 We can add that but do you think that's a useful case?

**Comment by ashmaroli** [comment]
Since users are asking for the homepage to be something other the `/pages/` route, I think it'd be best if user could choose whatever supported route to be their indexRoute..

**Comment by mertkahyaoglu** [comment]
@ashmaroli 👍 Added all other routes as well.

**Comment by ashmaroli** [comment]
The implementation LGTM!
Does this need test coverage?

**Comment by mertkahyaoglu** [comment]
Absolutely but it's a bit tricky to test so I skipped it thinking code is safe. We'll see if we get any issue about this 😅

**Review by ashmaroli — APPROVED** [review]

**Pull request merged**
