### PR TITLE
Move frontend to root folder

### PR DESCRIPTION
**Pull request by mertkahyaoglu**

### CODE REVIEW

**Comment by mertkahyaoglu** [comment]
@benbalter Do we need `script/return-to-pwd` anymore?

**Comment by benbalter** [comment]
> Do we need script/return-to-pwd anymore?

The build script still needs to `cd` into `src`, right?

I'm not tied to it... my motivation was that running `script/server`, `script/build`, `script/cibuild`, etc. shouldn't leave you in a different folder than when you started... if that's not the case any more, and it's not necessary, by all means, 💀 it.

**Comment by mertkahyaoglu** [comment]
> The build script still needs to cd into src, right?

Ops, forgot that.

**Comment by mertkahyaoglu** [comment]
> The build script still needs to cd into src, right?

No, it does not. `package.json` in the root now.

**Comment by mertkahyaoglu** [comment]
@benbalter is it cache that fails travis?

**Comment by mertkahyaoglu** [comment]
@benbalter Anything else you want me to add?

**Comment by benbalter** [comment]
I suspect we want to `.gitignore` the compiled/built site? I'll follow up with another PR that builds the site prior to releasing, otherwise,

LGTM.

**Pull request merged**
