### PR TITLE
Separate frontend messages into a file

### LINKED ISSUE #241: Separate frontend messages into a file
Currently some messages like the followings;

* `Are you sure that you want to delete FILENAME ?`
* `No data files found.`
* `Are you sure that you want to delete FILENAME ?`

are hardcoded into components (e.g. [here](https://github.com/jekyll/jekyll-admin/blob/master/src/containers/views/DocumentEdit.js#L61)). When we want to change the `delete message`, for example, we have to make changes to all of files that contains it. It would be nice to separate all messages into a file like `messages.js` so we can make changes to only that file when we want.

In addition, this would help us implement #99 easily in the future.

### PR DESCRIPTION
**Pull request by mertkahyaoglu**
Resolves #241

### CODE REVIEW

**Comment by ashmaroli** [comment]
I think there should also be a set of sort of success messages:
```
"[FILE] deleted."
"[FILE] created."
"[FILE] renamed."
"Changes saved successfully"
```

**Comment by mertkahyaoglu** [comment]
Totally forgot them. Thanks 👍

**Comment by mertkahyaoglu** [comment]
I don't know if there is a better way for handling these messages. I'm open to suggestions to improve the readability.

**Comment by ashmaroli** [comment]
@mertkahyaoglu I'm running the `server-frontend` script on latest `master` and:
- creating a new `Page` / `Post` does not display any flash messages.
- Deleting an existing `Page` / `Post` does not display a successfully deleted flash message.
- Deleting an uploaded static file does not display a flash message.

**Comment by mertkahyaoglu** [comment]
Yeap, those messages are intentionally left missing because after those actions you can see the results directly. But for completeness, we should still add them.

**Pull request merged**
