### PR TITLE
restrict meta-key length

### PR DESCRIPTION
**Pull request by ashmaroli**
restrict metadata-key length to a max 21 characters in compliance with current style definitions
ja2

### CODE REVIEW

**Comment by benbalter** [comment]
> in compliance with current style definitions

What do you mean by that?

**Comment by ashmaroli** [comment]
> in compliance with current style definitions
>
> What do you mean by that?

`.meta-key .key-field` class currently has a `max-width` of `190px` which supports just 21 characters to be visible. If at a later date, the max-width changes, the `maxlength` attrib can be changed accordingly.

**Comment by mertkahyaoglu** [comment]
@benbalter What do you think about this? Shall we limit meta key length? Another option would be to increase input width.

**Comment by ashmaroli** [comment]
@DirtyF, why the downvote?

**Comment by benbalter** [comment]
The text input may be limited to 21 characters visible at any given time, but there's no reason meta keys can't extend well beyond that. We shouldn't be limiting our data model due to limitations in the UI. If anything, the opposite should be the case. What's the harm with the text scrolling within the textbox for users with large keys?

**Comment by ashmaroli** [comment]
point taken.

**Pull request closed without merging**
