### PR TITLE
Metafields design tweaks

### LINKED ISSUE #139: Creating a New Metadata Field Doesn't Automatically Create A Valid Field Name, Or Indicate the User Can
When a user adds a "New meta-data field" they should 
1) not have to rename the field by default, and 
2) it should be intuitive that there's a way to do so, and
3) the field should instruct them how to make a valid field name, or not allow them to make an invalid field.

The current view (screenshot attached) creates an invalid field name by default (e.g. `New Field 14`), and there's no way of telling that the user can click into the box to edit it, nor is there any way to enforce or instruct them to use a proper field name.

screen shot 2016-08-18 at 7 44 48 pm

### PR DESCRIPTION
**Pull request by mertkahyaoglu**
Closes #139 

screen shot 2016-10-29 at 6 19 48 pm

### CODE REVIEW

**Comment by ashmaroli** [comment]
since the key-field class has a max-width, can we restrict and inform users to keep the key.length within a certain no. of characters?
I suspect a *super-long* key will have characters towards the end hidden..
ja

**Comment by mertkahyaoglu** [comment]
That's a good idea. Could you create a follow-up PR for that?

**Comment by ashmaroli** [comment]
okay.. but I wont be able to add the validation alert..

**Comment by mertkahyaoglu** [comment]
What about adding just `maxlength` attribute? Would that be enough?

**Comment by ashmaroli** [comment]
that would be enough.. will create a PR soon..

**Pull request merged**
