### PR TITLE
Create new URLable module to include API URL and HTTP URLs in each response

### PR DESCRIPTION
**Pull request by benbalter**
This creates a new URLable module, that gets included in all response classes to provide `http_url` and `api_url` fields (and tests to ensure they're valid for all associated resources).

* `http_url` - Absolute URL to the HTTP(S) rendered/served representation of this resource (e.g., what you're put in your browser to see the thing.

* `api_url` - Absolute URL to the API representation of this resource (e.g., the API endpoint for that thing).

This is a partial fix for https://github.com/jekyll/jekyll-admin/issues/164, with the idea being that the front end would use `http_url` (the absolute URL) rather than `url` (Jekyll's internal representation of the path to the object relative to the base url) when linking to resources. 

This PR should also resolve port issues from the test server, as the URL contains the local serve's port, as retrieved from the site config.

### CODE REVIEW

**Comment by mertkahyaoglu** [comment]
Tested locally and it works great. What about excluding `url` ? I guess we don't need it anymore.

**Comment by benbalter** [comment]
> What about excluding url ? I guess we don't need it anymore.

:metal: great idea. I would suggest doing that in a subsequent PR, as that should be a breaking change in terms of the front end (which I believe relies on the URL field today.

If I merge this now, you can update the front end at your convenience, and then we can remove the URL field (or you can do so in your PR by following the examples in APIable), and `master` should continue to be stable.

**Comment by mertkahyaoglu** [comment]
👍

**Comment by mertkahyaoglu** [comment]
I think we cannot get rid of that `url`. What will we use for documents in an unwritten collection like `puppies` ?

**Comment by benbalter** [comment]
> What will we use for documents in an unwritten collection like puppies ?

What do you mean? For the path?

**Comment by mertkahyaoglu** [comment]
I mean if you check `http://localhost:4000/_api/collections/puppies/rover.md`, `http_url` is null for  that document. I didn't get why is that for documents which their collection is not writable, Implemented [here](https://github.com/jekyll/jekyll-admin/blob/master/lib/jekyll-admin/urlable.rb#L9).

**Comment by mertkahyaoglu** [comment]
@benbalter Ah, sorry for the silly question. What was I thinking? Yeah, we shouldn't have `http_url` for the documents that don't have html in _site folder. I didn't notice that for `puppies` that till now 😬 .

The problem is how does the front-end now that documents in a collection is not writable. Because all documents use the same component which relies on the `http_url` field for previewing. If some documents do not have it, front-end crashes.

**Comment by mertkahyaoglu** [comment]
And I think I found a solution for that. Now creating a PR.

**Comment by benbalter** [comment]
> If some documents do not have it, front-end crashes.

Hmm. Gotcha. Is it possible to hide the preview button if `http_url` is null? I don't know what URL we'd show for data files or collections that don't render otherwise.

**Comment by mertkahyaoglu** [comment]
Yep. Just implemented that with #167

**Pull request merged**
