### PR TITLE
Adapt Frontend to the API

### LINKED ISSUE #23: Frontend can't assume assume port
Right now, the front end [assumes the server is running on `localhost:3004`](https://github.com/jekyll/jekyll-admin/blob/master/lib/jekyll/admin/public/src/constants/api.js#L6-L21). 

While the default server port will be `4000`, users can set that via a flag, so we shouldn't assume that either. 

Ideally, the server would get the port from the URL it's being requested from, or from the server directly.

### PR DESCRIPTION
**Pull request by mertkahyaoglu**
Closes #23, #24 

- [x] Update API endpoints
- [x] Remove mock API to use the real one
- [x] Adapt actions, reducers and components to the API
- [x] Fix tests
- [x] Replaces `POST` with `PUT` again
- [x] Fix list, edit and create views (depends on #30, #41)

### CODE REVIEW

**Comment by mertkahyaoglu** [comment]
This PR depends on #30. I'm in favor of removing defaults as well because right now updating a document/page adds defaults to the front matter.

**Comment by benbalter** [comment]
> Replaces POST with PUT again

If I did this backwards, I don't recall where things landed, and easy enough to change back on the server side, if you think it should be one way or the other.

**Comment by mertkahyaoglu** [comment]
I also think PUT is better but had to change it cause of Ankur implementation.

**Comment by benbalter** [comment]
> I also think PUT is better

If there's a change you'd like on the server side, I'd implement things the way you think it should be here, and open an issue describing the desired behavior, and we'll take care of it (I'm not sure which endpoints your referring to specifically).

**Comment by mertkahyaoglu** [comment]
@benbalter Updating config adds `posts` to the `collections` section in the `_config.yml` file. Here are the steps to reproduce the issue.

1._config.yml includes the following content;

``` yaml
title: Your awesome title
collections:
  test:
    foo: bar
    output: true
```

2.Update the config

3._config.yml file now includes the following content;

``` yaml
title: Your awesome title
collections:
  posts:
    output: true
  test:
    foo: bar
    output: true
```

4.Delete the following lines;

``` yaml
posts:
  output: true
```

5.It deletes those lines from the file but the response to the front-end still has them.

**Comment by benbalter** [comment]
@mertkahyaoglu would you mind opening a dedicated issue for what you just described (copy and paste is fine). That way we can track fixing that server-side bug regardless of the client-side implementation you're working on here (and then it shouldn't be seen as a blocker).

**Comment by benbalter** [comment]
Chatted with @mertkahyaoglu via Slack, and although there's a few things still not yet implemented, this LGTM, so that we can keep subsequent PR's smaller.

**Pull request merged**
