### PR TITLE
Adjust gemspec to allow use with Jekyll 4.0

### PR DESCRIPTION
**Pull request by zocoi**
Since jejyll 4 is released, bump up the requirement version

### CODE REVIEW

**Comment by ashmaroli** [comment]
@zocoi Couple of comments (FYI):
- Dependency `"jekyll", "~> 4"` means the next release can't be run with Jekyll 3.x. That would be bad as the majority of the users would still be using Jekyll 3.x series.
Instead opt for **`"jekyll", ">= 3.3", "< 5.0"`**
- IMO, it'd be better if Travis would use the lowest common Ruby version which is `rvm 2.4`

**Comment by tosbourn** [comment]
Just heard about this project and would love to see this change make it in so I can try jekyll-admin on my blog. 💜

**Comment by mertkahyaoglu** [comment]
@ashmaroli I think this is ready to go, right?

**Comment by ashmaroli** [comment]
> I think this is ready to go

Not quite. First, I shall merge `#497`. Then reduce the scope of changes in this PR..

**Comment by mertkahyaoglu** [comment]
Good 👍  @zocoi We can merge this after conflicts are resolved then.

**Comment by ashmaroli** [comment]
@zocoi I've thinned out the changes made in this branch to keep the PR focused to the primary intention.
Regarding the use of Node 8 for testing, we can bump if necessary in the future. For now, tests run on it just fine.

**Comment by ashmaroli** [comment]
Thank you for your contribution @zocoi :smiley:

**Comment by zocoi** [comment]
you're welcome, thanks for responding to this PR quickly :)

**Pull request merged**
