### PR TITLE
Release v0.8.2

### PR DESCRIPTION
**Pull request by mertkahyaoglu**

### CODE REVIEW

**Comment by ashmaroli** [comment]
Since its been so long since the last release, I suggest we ship a `v0.9.0` with Jekyll 4.0 support and newer versions of node dependencies..

**Comment by mertkahyaoglu** [comment]
@ashmaroli You think can we release it after #492 ?

**Comment by ashmaroli** [comment]
Apart from that PR, I feel our `Jekyll::Commands::Serve` monkey-patch needs some corrections to be truly in sync with Jekyll..

**Comment by mertkahyaoglu** [comment]
OK. I'm leaving the release to you then. Feel free to make your first release as a maintainer whenever it's all good to go 🎉

**Comment by ashmaroli** [comment]
Thank you very much :smiley:

**Pull request closed without merging**
