### PR TITLE
Changed Danish translations to something more sensible

### PR DESCRIPTION
**Pull request by BlueWombat**
Took the liberty of updating the translation so it makes a little more sense to Danes :-)

### CODE REVIEW

**Comment by mertkahyaoglu** [comment]
Thanks @BlueWombat 👍

**Comment by ashmaroli** [comment]
My apologies to everyone who understands the language. I had used Google Translate to generate the text. Thanks for improving it @BlueWombat :smiley:

**Comment by BlueWombat** [comment]
Welcome @mertkahyaoglu :-)

Hi @ashmaroli, yeah that as quite obvious :P People ould've understood it, but I felt I might as ell keep improving it, since I wrote the initial translation ;-)

I also plan to get to orkingg on the general project roadmap, just haven't had time yet :-)

**Comment by ashmaroli** [comment]
I'll make a note to ping you the next time I add a translation. :wink:

**Comment by BlueWombat** [comment]
Please do, the amount of stuff needing translation in this project isn't exactly overwhelming anyway, so I can probably do it in a matter of minutes anyway :-)

Took me longer to get my fork updated and writing the pull request, than the translation :P

**Pull request merged**
