### PR TITLE
Release v0.2.0

### PR DESCRIPTION
**Pull request by mertkahyaoglu**
It's been a while since the last release. I think we have enough to release a minor one 🎉

### CODE REVIEW

**Comment by DirtyF** [comment]
@mertkahyaoglu maybe you could use some @jekyllbot magic for releases?

/cc @benbalter @parkr

**Comment by mertkahyaoglu** [comment]
@DirtyF That would be 🆒

**Comment by DirtyF** [comment]
@mertkahyaoglu PR on its way :)

**Comment by mertkahyaoglu** [comment]
@DirtyF Should we close this to try it out ?

**Comment by mertkahyaoglu** [comment]
Second, I have no ideo how @jekyllbot works 😬

**Comment by DirtyF** [comment]
@mertkahyaoglu @jekyllbot will merge and depending on the associated category will write the change in a History.markdown file. Pushing a new release is as easy as pushing a tag!

see. https://jekyllrb.com/docs/maintaining/merging-a-pull-request/#merging

**Comment by mertkahyaoglu** [comment]
Thanks @DirtyF 👍

**Comment by benbalter** [comment]
@mertkahyaoglu 🎉 let me know if you need help pushing to Rubygems.

**Comment by mertkahyaoglu** [comment]
@DirtyF So @jekyllbot merge +minor will update the version in `version.rb` and release a new version on rubygems.org, right?

@benbalter I was using `script/release` after updating version.rb. If @jekyllbot will handle these, it's super easy.

**Comment by ashmaroli** [comment]
> So @jekyllbot merge +minor will update the version in version.rb and release a new version on rubygems.org, right? Or am I asking too much ?

@mertkahyaoglu I think JekyllBot doesn't alter `version.rb` or push a new gem. What `@jekyllbot: merge+minor` does is:
  - merge the concerned PR to main-branch.
  - apply relevant labels if not assigned already  
    (e.g. `merge+dev` => `fix` & `internal` labels)
  - update `History.markdown` with PR title under relevant heading.  
    (e.g. `merge+minor` will add to `Minor Enhancements`, `merge+dev` will add to `Development Fixes`)

**Comment by mertkahyaoglu** [comment]
Thanks @ashmaroli I was dreaming too much automation :trollface:

**Comment by parkr** [comment]
@mertkahyaoglu It would be really cool to be able to have @jekyllbot create a version bump in the pull request! It could update the changelog (history.markdown) and the `version.rb` or the `.gemspec` if no `version.rb` file exists. Neat idea!

**Comment by mertkahyaoglu** [comment]
@parkr I would love to work on that if you guide me 👍

**Comment by parkr** [comment]
It's all in here... 😄 https://github.com/parkr/auto-reply#writing-custom-handlers

**Comment by mertkahyaoglu** [comment]
Awesome! I always wanted to write some Go for a good reason :man_dancing:

**Comment by DirtyF** [comment]
@mertkahyaoglu FYI you should be abile to use @jekyllbot commande on `jekyll-admin`repo now 🎉

**Comment by mertkahyaoglu** [comment]
@DirtyF Awesome 🎉

**Pull request merged**
